SERVER_HOST=127.0.0.1
SERVER_PORT=8090
SERVER_READ_TIMEOUT=30s
SERVER_WRITE_TIMEOUT=30s
SERVER_IDLE_TIMEOUT=30s

LOGGER_LEVEL=debug

APP_STORAGE_TYPE=memory

PG_HOST=127.0.0.1
PG_PORT=25432
PG_USERNAME=user
PG_PASSWORD=password
PG_DATABASE=calendar